### ISSUE TITLE
Problem of installing brew gcc@7 and falaise

### ISSUE THREAD

**Issue by MHoballah** [SuperNEMO-DBD/brew#11]
Dear Ben,

We had problems installing falaise brew at Lyon when installing gcc@7.
Thanks for the help for the new student Malak Hoballah, cheers

                                  Laurent and Malak 

==> Installing gcc@7
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.xz
Already downloaded: /pbs/home/m/mhoballa/.cache/Homebrew/downloads/07bf377bb288d33327b5db269277c2fee319dafda4a3c8b7970bfb347858257b--gcc-7.4.0.tar.xz
==> ../configure --with-bugurl=https://github.com/Linuxbrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/pbs/home/m/mhoballa/soft_supernemo/snemo-sdk/include --with-specs=%{!st
==> make
Last 15 lines from /pbs/home/m/mhoballa/.cache/Homebrew/Logs/gcc@7/02.make:
checking for ld used by GCC... ld
checking if the linker (ld) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... yes
checking for iconv declaration... install-shextern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
configure: updating cache ./config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depdir commands
mkdir -p -- .deps
make[2]: Leaving directory `/tmp/gcc@7-20190419-34151-bpk1ny/gcc-7.4.0/build'
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory `/tmp/gcc@7-20190419-34151-bpk1ny/gcc-7.4.0/build'
make: *** [all] Error 2

READ THIS: https://github.com/SuperNEMO-DBD/brew/issues
Please do not report this issue to Homebrew/brew or Homebrew/core,
which support macOS only."

These open issues may also help:
Review RPATH in *link section of specs file for gcc-7 https://github.com/SuperNEMO-DBD/homebrew-core/issues/1
/pbs/home/m/mhoballa/soft_supernemo(1)>^C
/pbs/home/m/mhoballa/soft_supernemo(130)>^C
/pbs/home/m/mhoballa/soft_supernemo(130)>^C
/pbs/home/m/mhoballa/soft_supernemo(130)>brew test falaise
Error: Testing requires the latest version of falaise

**Comment by drbenmorgan** [comment]
Hi @MHoballah, could you run:

```console
brew gist-logs gcc@7
```

and post the link here please?

**Comment by drbenmorgan** [comment]
Also note that you *don't* have to install Falaise by hand at CC-IN2P3. Singularity containers are available as documented in the README:

- https://github.com/SuperNEMO-DBD/brew#installing-images
- https://github.com/SuperNEMO-DBD/brew#using-an-image

and in the docs from the Annecy tutorial:

- http://nile.hep.utexas.edu/cgi-bin/DocDB/ut-nemo/private/DisplayMeeting?conferenceid=802

**Comment by MHoballah** [comment]
Hello,
Here's the link: 

https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew

Thanks in advance,
Malak

**Comment by drbenmorgan** [comment]
Thanks, but that's not a gist link. It looks like it's asking you to set up an access token. Did it print:

```
You can create a new personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.bash_profile

GitHub User: 
```

Create that token and follow the instructions for adding it to your shell profile, or run:

```
$ HOMEBREW_GITHUB_API_TOKEN=your_token_here brew gist-logs gcc@7
```

**Comment by MHoballah** [comment]
sorry, this is the link:
https://gist.github.com/d3bc534ae5bda417fe47b17eacdea6e4

**Comment by drbenmorgan** [comment]
O.k., can you run 

```
$ brew ls --versions
```

and post the output please?

**Comment by MHoballah** [comment]
sure:

binutils 2.32
bzip2 1.0.6_1
curl 7.64.0
gcc@7 7.4.0
gettext 0.19.8.1_1
glibc 2.23
gmp 6.1.2_2
gpatch 2.7.6
isl 0.20
libbsd 0.8.3
libmpc 1.1.0
linux-headers 4.4.80
m4 1.4.18
mpfr 4.0.1
ncurses 6.1
openssl 1.0.2q_2
pcre2 10.32
pkg-config 0.29.2_1
zlib 1.2.11

**Comment by drbenmorgan** [comment]
The problem is likely caused by the presence of glib, and looks like the error isn't fundamentally due to gcc. Could you post the exact sequence of commands you used to try and install falaise please?

**Comment by MHoballah** [comment]
I followed the steps in this link:

https://github.com/SuperNEMO-DBD/brew

$ sudo apt-get install ca-certificates curl file g++ git locales make uuid-runtime libx11-dev libxpm-dev libxft-dev libxext-dev libglu1-mesa-dev flex texinfo
$  git clone https://github.com/SuperNEMO-DBD/brew.git snemo-sdk
$ eval $(./snemo-sdk/bin/brew shellenv)
$ brew snemo-doctor
$ brew snemo-bootstrap

but did not go past "brew snemo-bootstrap" due to an error and  fails in installations.
The Error:
"
Skipping install of gcc@7 formula. It is already up-to-date.
Using gcc@7
Installing patchelf formula. It is not currently installed.
Error: An exception occurred within a child process:
  RuntimeError: The requested Homebrew GCC was not installed. You must:
  brew install gcc@7
"
but i cant manage to install  gcc@7. It's either exiting due to a time-out, or my connection to cca.in2p3.fr is closed by a remote host.

**Comment by drbenmorgan** [comment]
Thanks, I think I see what's happened. What you'll need to do is:

1. Run `brew rm $(brew ls)` to remove everything
2. Run `brew snemo-doctor` again, and post the output here.
   - It's possible that the errors are caused by the scripts listed in the gist you posted (https://gist.githubusercontent.com/MHoballah/d3bc534ae5bda417fe47b17eacdea6e4/raw/05321a88e8af968c706c9ff26d942e69455030ac/00.doctor.out, see the entries in `/pbs/software`)
4. Run `brew snemo-bootstrap` again.
5. If it fails, don't do anything else, and post the full output here as this will lead to the formula that failed to install.

**Comment by MHoballah** [comment]
"brew snemo-doctor" output:
Please note that these warnings are just used to help the SuperNEMO maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /pbs/software/centos-7-x86_64/xrootd/4.8.1/bin/xrootd-config
  /bin/curl-config
  /bin/xml2-config
  /bin/euca-generate-environment-config
  /bin/pcre-config
  /bin/neon-config
  /bin/freetype-config
  /bin/icu-config
  /bin/libpng15-config
  /bin/python2.7-config
  /bin/krb5-config
  /bin/nss-util-config
  /bin/libusb-config
  /bin/nspr-config
  /bin/python2-config
  /bin/ncurses5-config
  /bin/gdlib-config
  /bin/nss-softokn-config
  /bin/nss-config
  /bin/euscale-delete-launch-config
  /bin/apr-1-config
  /bin/pkg-config
  /bin/euscale-create-launch-config
  /bin/python-config
  /bin/net-snmp-config
  /bin/libpng-config
  /bin/libgnutls-config
  /bin/log4cpp-config
  /bin/gsl-config
  /bin/ncursesw5-config
  /bin/apu-1-config

Warning: An outdated version (1.8.3.1) of Git was detected in your PATH.
Git 2.7.0 or newer is required for Homebrew.
Please upgrade:
  brew install git

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You may encounter build failures with some formulae as
brew is being run in an unsupported configuration
In these cases, please raise an issue at https://github.com/SuperNEMO-DBD/homebrew-core/issues

**Comment by drbenmorgan** [comment]
O.k., that looks better. See what happens with the delete/reinstall, and we can try and track down the formula causing the problem.

**Comment by MHoballah** [comment]
Hello again,
Thank you for your help.

I managed to finish the part we had problems in. ran the "brew test falaise" and it worked.
To install the images using Singularity I used "singularity pull docker://supernemo/falaise" and it worked. (following the guide in https://github.com/SuperNEMO-DBD/brew )
But the cross checking of the image using "singularity exec --home $HOME falaise.simg brew test falaise" (at cc lyon) failed with the following error.

Thanks again for your help!
Best,
Malak

error: could not lock config file /opt/supernemo/Homebrew/.git/config: Read-only file system
Testing falaise
==> /opt/supernemo/Cellar/falaise/HEAD-bec42c8_1/bin/flsimulate -o test.brio
Last 15 lines from /pbs/home/m/mhoballa/.cache/Homebrew/Logs/falaise/test.01.flsimulate:
                            WWW : http://cern.ch/geant4
*************************************************************

HepRandomEngine::put called -- no effect!
[notice:virtual void mctools::g4::manager::_init_detector_construction():1476] Detector construction...
[notice:virtual void mctools::g4::manager::_init_physics_list():1490] Physics list initialization...
[notice:virtual void mctools::g4::manager::_init_run_action():1504] Run action initialization...
[notice:virtual void mctools::g4::manager::_init_event_action():1530] Event action initialization...
[notice:virtual void mctools::g4::manager::_init_primary_generator_action():1543] Primary generator action initialization...
[notice:virtual void mctools::g4::manager::_init_tracking_action():1562] Tracking action initialization...
[notice:virtual void mctools::g4::manager::_init_stepping_action():1572] Stepping action initialization...
[notice:virtual void mctools::g4::manager::_init_stacking_action():1582] Stacking action initialization...
[notice:virtual void mctools::g4::manager::initialize_impl():949] G4 kernel initialization...
flsimulate : Setup/run of simulation threw exception
[void mctools::g4::detector_construction::write_tmp_gdml_file():1313: Cannot create GDML temporary file !]
Error: falaise: failed
Failed executing:
/opt/supernemo/Homebrew/Library/Homebrew/formula.rb:1921:in `block in system'
/opt/supernemo/Homebrew/Library/Homebrew/formula.rb:1858:in `open'
/opt/supernemo/Homebrew/Library/Homebrew/formula.rb:1858:in `system'
/opt/supernemo/Homebrew/Library/Taps/supernemo-dbd/homebrew-core/Formula/falaise.rb:27:in `block in <class:Falaise>'
/opt/supernemo/Homebrew/Library/Homebrew/formula.rb:1732:in `block (3 levels) in run_test'
/opt/supernemo/Homebrew/Library/Homebrew/utils.rb:539:in `with_env'
/opt/supernemo/Homebrew/Library/Homebrew/formula.rb:1731:in `block (2 levels) in run_test'
/opt/supernemo/Homebrew/Library/Homebrew/formula.rb:870:in `with_logging'
/opt/supernemo/Homebrew/Library/Homebrew/formula.rb:1730:in `block in run_test'
/opt/supernemo/Homebrew/Library/Homebrew/formula.rb:1971:in `block in mktemp'
/opt/supernemo/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/opt/supernemo/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/opt/supernemo/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/opt/supernemo/Homebrew/Library/Homebrew/formula.rb:1970:in `mktemp'
/opt/supernemo/Homebrew/Library/Homebrew/formula.rb:1724:in `run_test'
/opt/supernemo/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/opt/supernemo/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/opt/supernemo/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/opt/supernemo/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/opt/supernemo/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/opt/supernemo/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/opt/supernemo/Homebrew/Library/Homebrew/test.rb:27:in `<main>'

**Comment by drbenmorgan** [comment]
I think the test error is expected due to #10, so use the workaround in there for now. I’ll update the Singularity container in the next few days.
