### ISSUE TITLE
failure in brewing falaise 4 on ubuntu 18.04

### ISSUE THREAD

**Issue by emchauve** [SuperNEMO-DBD/brew#15]
while putting falaise 4 on a fresh installation of ubuntu 18.04, brew snemo-bootstrap is failing at the step of **linux-pam** :
`Error: No available formula with the name "linuxbrew/extra/linux-pam" (dependency of falaise)`

a missing formula ?

**Comment by drbenmorgan** [comment]
Hi @emchauve, this should now be fixed, so please try running

```
$ brew update
...
$ brew install falaise --cc=gcc-7
```

That last command should be sufficient as the bootstrap appears to have got to the stage of installing Falaise and its dependencies.

**Comment by emchauve** [comment]
fixed, cheers !
