### ISSUE TITLE
USER is set incorrectly in Singularity

### ISSUE THREAD

**Issue by drbenmorgan** [SuperNEMO-DBD/brew#4]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to this repository again.**

- [x] ran a `brew` command and reproduced the problem with multiple formulae? 
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, supernemo-dbd-core formula?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Run `brew test falaise` in Singularity at CC-IN2P3 to test usage of images for production. Full command was as instructed in the README:

```
$ singularity exec --home $HOME falaise.simg brew test falaise
```

# What happened (include command output)

`flsimulate` will throw an exception as uncle to create temporary GDML file. Reported by @cherylepatrick in https://github.com/SuperNEMO-DBD/starterkit/issues/6
 
<details>
  <summary>Command output</summary>
  <pre>
  
[void mctools::g4::detector_construction::write_tmp_gdml_file():1313: Cannot create GDML temporary file !]
  </pre>
</details>

# What you expected to happen

The command should have run the tests and produced the output as shown in the README

# Step-by-step reproduction instructions (by running `brew` commands)

Login to CC-IN2P3 interactive node:

```
$ singularity pull docker://supernemo/falaise
$ singularity exec --home $HOME falaise.simg brew test falaise
```

It may not always occur as the likely cause is:

1. The Docker image sets `USER` to `snemo`
2. In Singularity, the actual user is the CC-IN2P3 user (`whoami`)
3. `flsimulate` uses value of `USER` to create a directory in `tmp`.
4. If two different users run on the same node, they will each create a `/tmp/snemo` directory.
5. The second user to run will see the error as `/tmp/snemo` will be owned by the first.

**Comment by drbenmorgan** [comment]
Fix will either be in the entry point script (change `USER` to `whoami`), or in a proper Singularity recipe. Need to RTF(Singularity)M first!

**Comment by cherylepatrick** [comment]
Not the end of the world if it has to go in the script!

**Comment by drbenmorgan** [comment]
Reading the Singularity info, it looks like the first things to try are:

1. Don't set `USER` in the Dockerfile's `ENV` as that gets explicitly set in the Singularity container. *However*, check whether `USER` is set in the resulting shell sessions. If not, might need to explicitly use a login shell (`/bin/bash -l`) for `SHELL` etc.
2. Recommend use of `singularity run` over `singularity shell`. The former *should* use the `ENTRYPOINT/CMD` from the Docker image. Check also behaviour of `singularity exec` and whether is uses `ENTRYPOINT/CMD`.
